---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: domonitors.douz.com
spec:
  group: douz.com
  scope: Namespaced
  names:
    plural: domonitors
    singular: domonitor
    kind: DoMonitor
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                ingressName:
                  type: string
                  description: "The name of the associated Ingress"
                monitorID:
                  type: string
                  nullable: true
                  description: "The DigitalOcean Uptime monitor ID"
                host:
                  type: string
                  description: "The monitored hostname"
                alerts:
                  type: object
                  properties:
                    uptimeAlertID:
                      type: string
                      nullable: true
                      description: "The DigitalOcean Uptime alert ID"
                    latencyAlertID:
                      type: string
                      nullable: true
                      description: "The DigitalOcean latency alert ID"
                    sslExpiryAlertID:
                      type: string
                      nullable: true
                      description: "The DigitalOcean SSL expiry alert ID"
                config:
                  type: object
                  properties:
                    email:
                      type: string
                      description: "The email address to send alerts to"
                    emailAlert:
                      type: boolean
                      description: "Whether to send email alerts"
                    slackWebhook:
                      type: string
                      description: "The Slack webhook URL"
                    slackChannel:
                      type: string
                      description: "The Slack channel to send alerts to"
                    slackAlert:
                      type: boolean
                      description: "Whether to send Slack alerts"
                    latencyThreshold:
                      type: integer
                      description: "The latency threshold in milliseconds"
                    latencyPeriod:
                      type: string
                      description: "The period in minutes to check latency"
                    sslExpiryPeriod:
                      type: integer
                      description: "The period in days to check SSL expiry"
