apiVersion: v2
name: do-uptime-operator
description: Kubernetes operator to manage DigitalOcean Uptime monitors and alerts from Ingress annotations
type: application
version: 0.1.1
appVersion: "3a61d10a4cbf85e4f235d6762eb1fae0f8ba42d6"
home: https://github.com/douz/do-uptime-kubernetes-operator
sources:
  - https://github.com/douz/do-uptime-kubernetes-operator
keywords:
  - kubernetes
  - operator
  - digitalocean
  - uptime
maintainers:
  - name: douz
