apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "do-uptime-operator.fullname" . }}
  labels:
    {{- include "do-uptime-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "do-uptime-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "do-uptime-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "do-uptime-operator.serviceAccountName" . }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - kopf
            - run
            - --standalone
            - --all-namespaces
            - domonitor_operator/domonitor_operator.py
          env:
            - name: DIGITALOCEAN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "do-uptime-operator.secretName" . }}
                  key: token
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
