{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "do-uptime-operator.fullname" . }}
  labels:
    {{- include "do-uptime-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "events", "namespaces"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["douz.com"]
    resources: ["domonitors"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "do-uptime-operator.fullname" . }}
  labels:
    {{- include "do-uptime-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "do-uptime-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "do-uptime-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
