{{- if .Values.digitalocean.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "do-uptime-operator.secretName" . }}
  labels:
    {{- include "do-uptime-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ required "Set digitalocean.token when digitalocean.createSecret=true" .Values.digitalocean.token | quote }}
{{- end }}
